import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { IsUserLoggedContext } from './context/isUserLogged'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element => {
  return (
    <html lang='en'>
      <IsUserLoggedContext>
        <body className={inter.className}>{children}</body>
      </IsUserLoggedContext>
    </html>
  )
}

export default RootLayout
